### ISSUE TITLE
Make get_* methods properties

### ISSUE THREAD

**Issue by paulromano** [svalinn/pydagmc#12]
There are a bunch of `get_*` methods, such as `Group.get_volumes`, `Volume.get_surfaces`, and `DAGSet.get_triangle_coords` that do not take any arguments. If we don't anticipate adding arguments to those methods in the future, they could be made into properties within the `get_` prefix, i.e.
```Python
class Group(DAGSet):
    ...
    @property
    def volumes(self):
        ...

class Volume(DAGSet):
    ...
    @property
    def surfaces(self):
        ...
```

Another suggestion is that in the cases where these methods are returning a dictionary of ID to object, simply return a list of the objects as that is the more basic collection.

**Comment by gonuke** [comment]
While it's true that lists are more basic collections, I think the dict of ID to object is useful since we use the ID in various places to refer to these sets.  If we needed to access an object via a list, we'd need to implement some kind of search to find which object has which ID.

**Comment by paulromano** [comment]
I've thought about this a lot with respect to OpenMC's API because we have a similar thing where we'll return dictionaries of {ID: object}. Over time, I've come to not like that design for a number of reasons:
1. It's inefficient if you just want a list of objects and the API always forces you to consume a dictionary first. I don't disagree that it's useful to have a dict of ID to object, but it's also useful in many circumstances to have a plain list of objects.
2. From a user's perspective, the method name seems to hint that it's going to return you an iterable of X, where X is a surface, volume, group, etc. A corollary to that is that iteration makes more sense when you can write code like:
    ```Python
    for surface in model.get_surfaces():
        # 'surface' is actually a surface, not an integer
    ```
3. If you really want that dict of ID to object, it's a one-liner:`{surf.id: surf for surf in model.get_surfaces()}`.

Anyway, just my two cents! I won't be hurt if you and/or @pshriwise reject the idea :smile:

**Comment by gonuke** [comment]
What if we implemented multiple functions, where the default getter provides a list, but there is also an method that returns a dict (by applying that one extra line)?

I could go either way as well, but returning a dict reduces some of the burden on the user/dev for some use cases.

**Comment by pshriwise** [comment]
I hear ya, @paulromano. I've had the same thought about those methods in OpenMC.

While I prefer one way of getting information, I like @gonuke's suggestion about the additional method in this case. For model generation algorithms or other algs, I think the lists make sense. When querying the model or debugging, the dictionary option is nice for the reasons already stated.

With some clever code I think we can implement the additional *_by_id option with just a few lines.
