### ISSUE TITLE
Review (reduce?) ad-hoc generation of objects

### ISSUE THREAD

**Issue by gonuke** [svalinn/pydagmc#14]
It seems that many of the methods to `get_volumes` and `get_surfaces` are generating new `Volume` and `Surface` objects on the fly each time they are called.  Perhaps these objects are lightweight wrappers, so it doesn't matter too much from a memory/performance point of view, but it seems a little redundant to always be generating new objects.

Is this an intentional design choice, or just a circumstance from development?

The alternative would be to populate a list/set/dict of these objects in each enclosing object either upon initialization or upon first request.

**Comment by gonuke** [comment]
Maybe this is a fundamental design question - whether or not/how much data we want to store in the pydagmc model vs querying the MOAB instance.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I think we can use both by setting an extra parameter in our init function, where users can choose which approach they would like to take.

Example:
```python
class Model:
    def __init__(self, use_cache=True):
        self.use_cache = use_cache
        self.volumes = {}
        self.surfaces = {}
    
    def get_volumes(self):
        if self.use_cache and self.volumes:
            return self.volumes
        else:
            # Logic to fetch volumes from somewhere
            return self.volumes
    
    def get_surfaces(self):
        if self.use_cache and self.surfaces:
            return self.surfaces
        else:
            # Logic to fetch surfaces from somewhere
            return self.surfaces
```

**Comment by gonuke** [comment]
I am happy to leave this and declare it s design choice.  This comes up often for me when creating convenience interfaces for MOAB-based data.  I experience this urge to cache things because it seems inefficient to always go back to the database.  However, that's kind of MOAB's design principle, so maybe it's just a "me" thing. 😀

**Comment by pshriwise** [comment]
Haha right on. I'm open to changing it in the future if needed. I don't think it would change anything about the API, but would more be an optimization we can add on if needed. Closing for now.
