### ISSUE TITLE
Update to newer MOAB for CI

### ISSUE THREAD

**Issue by gonuke** [svalinn/pydagmc#16]
I noticed that CI is using MOAB 5.3.1.  Is there a reason for not updating to something newer?

**Comment by ahnaf-tahmid-chowdhury** [comment]
I believe it has been added since we encountered an issue with MOAB, which has recently been resolved in DAGMC. I think we can move it to the latest version. I think, @pshriwise will be agreed with me.

**Comment by pshriwise** [comment]
No reason in particular. I was probably in a hurry to get testing setup for external contributions and selected that version on-the-fly. I'm not too worried about it as this all interacts through PyMOAB and in turn through MOAB's core interface -- both of which are pretty stable at this point. That said, no reason not to update it if someone has the bandwidth.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I have a request for you, @pshriwise. I recently created a [PR](https://bitbucket.org/fathomteam/moab/pull-requests/676) on the MOAB repo for wheel support, as I noticed you were one of the core developers of PyMOAB from your commits there. I would be very grateful if you could review the PR. Once it's released, I hope we can add the new MOAB to our CI.

**Comment by gonuke** [comment]
> No reason in particular. I was probably in a hurry to get testing setup for external contributions and selected that version on-the-fly. I'm not too worried about it as this all interacts through PyMOAB and in turn through MOAB's core interface -- both of which are pretty stable at this point. That said, no reason not to update it if someone has the bandwidth.

I can probably give it a shot, but this may also precipitate an HDF5 update since CI currently relies on the Ubuntu std HDF5 that is kind of old...
