### ISSUE TITLE
Slightly in consistent/unpredictable handling of multiple groups with same name

### ISSUE THREAD

**Issue by gonuke** [svalinn/pydagmc#18]
I have questions about group management vis-a-vis matching group names.  It looks like 
- it is possible to make new groups with the same name as an existing group, 
- each time the list of groups is queried, multiple groups with the same name are merged to a single group
- groups can only be merged if they have the same name

It seems that instead of adding new groups with overlapping names, we should just add items to existing groups so that there is never more than one group with the same name.

In the current state, it is possible for multiple groups with the same name to exist but only briefly and sporadically.

**Comment by pshriwise** [comment]
I'm not sure of a use case either, but I'm not sure that it's dangerous. From the look of the `DagMC::parse_properties` method, if there's already an entry for a property from a previous group set, then it will be added the property tagmap that is being generated. 

https://github.com/svalinn/DAGMC/blob/7e1cdb638b59ba22fd6ff0b09e94d8f658a1eadf/src/dagmc/DagMC.cpp#L1174

All the same, I think it's preferable not to have redundant `Group` instances hanging around. See comments in #15 on this. Thanks for these thoughts! I stood this up very quickly with the idea that it would primarily be a query interface, but it's nice to see it on it's way to something more.

**Comment by pshriwise** [comment]
Addressed by #17
