### ISSUE TITLE
fuel_pin.h5m used for tests should be updated

### ISSUE THREAD

**Issue by paulromano** [svalinn/pydagmc#6]
With the new consistency checks we added on `geom_dimension` and `category`, there are now some warnings emitted about the fuel_pin.h5m file that is used for testing, e.g.:
```
  /home/romano/codes/pydagmc/dagmc/dagnav.py:126: UserWarning: Assigned geom_dimension=4 to group 'mat:fuel'.
    warn(f"Assigned geom_dimension={self._geom_dimension} to {identifier}.")
```
I would update this file and send a PR, but it's being downloaded from a URL so it might be best for you to do that @pshriwise

**Comment by pshriwise** [comment]
Good call! Just updated the version of that test file online. After a re-run of CI I don't see those warnings any longer.

https://github.com/svalinn/pydagmc/actions/runs/7772008639/job/21193937830
